apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxcontroller
spec:
  selector:
    matchLabels:
      app: nginxapp_prod
  template:
    metadata:
      labels:
        app: nginxapp_prod
    spec:
      containers:
      - name: nginxcontainer
        image: prince2489/nginximage:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
