services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    # build: ./web
    image: prince2489/webimage
    hostname: web1
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    image: prince2489/webimage
    # build: ./web
    hostname: web2
    ports:
      - '82:5000'
  nginx:
    # build: ./nginx
    image: prince2489/nginximage
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2


